/**
 * Result HTML - Sample Seed Dataset
 * Embedded records mapped directly from Roll number and url file map.xlsx
 */

export const DEFAULT_INSTITUTE_CONFIG = {
    name: "CENTRALISED EXAMINATION BOARD",
    subHeading: "Centralised Examination Result",
    accreditation: "Secondary School Examination (Class IX & Class X)",
    address: "Central Examination Building, Education Zone - 110001",
    code: "CEB-SEC-2024",
    logoUrl: "https://cdn-icons-png.flaticon.com/512/2991/2991108.png",
    signatoryTitle: "Controller of Examinations",
    signatoryName: "Dr. S. K. Mukherjee",
    signatureUrl: "",
    watermarkText: "CENTRALISED RESULT",
    defaultGradingScale: "SECONDARY-100"
};

export const INITIAL_STUDENTS_DATA = [
    {
        "id": "STU-2024-001",
        "rollNo": "22287458",
        "dob": "31/12/2012",
        "name": "Aarav Sharma",
        "motherName": "Sunita Sharma",
        "fatherName": "Rajesh Sharma",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/745812.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-002",
        "rollNo": "22287459",
        "dob": "31/12/2012",
        "name": "Ananya Verma",
        "motherName": "Sunita Verma",
        "fatherName": "Rajesh Verma",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/745912.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-003",
        "rollNo": "22287460",
        "dob": "01/05/2013",
        "name": "Rohan Kulkarni",
        "motherName": "Sunita Kulkarni",
        "fatherName": "Rajesh Kulkarni",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746013.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-004",
        "rollNo": "22287461",
        "dob": "18/01/2011",
        "name": "Priya Nair",
        "motherName": "Sunita Nair",
        "fatherName": "Rajesh Nair",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746111.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-005",
        "rollNo": "22287462",
        "dob": "02/04/2010",
        "name": "Vikram Singh",
        "motherName": "Sunita Singh",
        "fatherName": "Rajesh Singh",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746210.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-006",
        "rollNo": "22287463",
        "dob": "17/12/2012",
        "name": "Ishaan Gupta",
        "motherName": "Sunita Gupta",
        "fatherName": "Rajesh Gupta",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746312.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-007",
        "rollNo": "22287464",
        "dob": "15/11/2009",
        "name": "Diya Patel",
        "motherName": "Sunita Patel",
        "fatherName": "Rajesh Patel",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746409.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-008",
        "rollNo": "22287465",
        "dob": "27/06/2008",
        "name": "Kabir Mehta",
        "motherName": "Sunita Mehta",
        "fatherName": "Rajesh Mehta",
        "classLevel": "Class IX",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/746508.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-009",
        "rollNo": "22282518",
        "dob": "19/08/2013",
        "name": "Sanya Rao",
        "motherName": "Sunita Rao",
        "fatherName": "Rajesh Rao",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/251813.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-010",
        "rollNo": "22287419",
        "dob": "13/01/2012",
        "name": "Aditya Joshi",
        "motherName": "Sunita Joshi",
        "fatherName": "Rajesh Joshi",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/741912.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-011",
        "rollNo": "22287420",
        "dob": "12/10/2013",
        "name": "Tara Sen",
        "motherName": "Sunita Sen",
        "fatherName": "Rajesh Sen",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742013.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-012",
        "rollNo": "22287421",
        "dob": "06/12/2011",
        "name": "Arjun Kapoor",
        "motherName": "Sunita Kapoor",
        "fatherName": "Rajesh Kapoor",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742111.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-013",
        "rollNo": "22287422",
        "dob": "12/12/2011",
        "name": "Meera Reddy",
        "motherName": "Sunita Reddy",
        "fatherName": "Rajesh Reddy",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742211.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-014",
        "rollNo": "22287423",
        "dob": "01/01/2013",
        "name": "Devansh Bose",
        "motherName": "Sunita Bose",
        "fatherName": "Rajesh Bose",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742313.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-015",
        "rollNo": "22287424",
        "dob": "15/08/2014",
        "name": "Riya Choudhury",
        "motherName": "Sunita Choudhury",
        "fatherName": "Rajesh Choudhury",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742414.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-016",
        "rollNo": "22287425",
        "dob": "06/05/2012",
        "name": "Kavya Saxena",
        "motherName": "Sunita Saxena",
        "fatherName": "Rajesh Saxena",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742512.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-017",
        "rollNo": "22287426",
        "dob": "22/01/2013",
        "name": "Yash Varma",
        "motherName": "Sunita Varma",
        "fatherName": "Rajesh Varma",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742613.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-018",
        "rollNo": "22287427",
        "dob": "01/01/2013",
        "name": "Anika Mishra",
        "motherName": "Sunita Mishra",
        "fatherName": "Rajesh Mishra",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742713.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-019",
        "rollNo": "22287428",
        "dob": "18/07/2011",
        "name": "Siddharth Roy",
        "motherName": "Sunita Roy",
        "fatherName": "Rajesh Roy",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742811.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-020",
        "rollNo": "22287429",
        "dob": "09/06/2012",
        "name": "Tanvi Bhat",
        "motherName": "Sunita Bhat",
        "fatherName": "Rajesh Bhat",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/742912.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-021",
        "rollNo": "22287430",
        "dob": "09/10/2011",
        "name": "Vivaan Aggarwal",
        "motherName": "Sunita Aggarwal",
        "fatherName": "Rajesh Aggarwal",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743011.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-022",
        "rollNo": "22287431",
        "dob": "02/10/2010",
        "name": "Navya Shrivastava",
        "motherName": "Sunita Shrivastava",
        "fatherName": "Rajesh Shrivastava",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743110.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-023",
        "rollNo": "22287432",
        "dob": "27/01/2011",
        "name": "Harsh Wardhan",
        "motherName": "Sunita Wardhan",
        "fatherName": "Rajesh Wardhan",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743211.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-024",
        "rollNo": "22287433",
        "dob": "23/08/2013",
        "name": "Sneha Pillai",
        "motherName": "Sunita Pillai",
        "fatherName": "Rajesh Pillai",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743313.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-025",
        "rollNo": "22287434",
        "dob": "02/12/2013",
        "name": "Rudra Pandey",
        "motherName": "Sunita Pandey",
        "fatherName": "Rajesh Pandey",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743413.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-026",
        "rollNo": "22287435",
        "dob": "10/03/2013",
        "name": "Avani Deshmukh",
        "motherName": "Sunita Deshmukh",
        "fatherName": "Rajesh Deshmukh",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743513.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-027",
        "rollNo": "22287436",
        "dob": "26/01/2012",
        "name": "Atharva Tripathi",
        "motherName": "Sunita Tripathi",
        "fatherName": "Rajesh Tripathi",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743612.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-028",
        "rollNo": "22287437",
        "dob": "12/01/2013",
        "name": "Kriti Malhotra",
        "motherName": "Sunita Malhotra",
        "fatherName": "Rajesh Malhotra",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743713.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-029",
        "rollNo": "22287438",
        "dob": "05/07/2013",
        "name": "Pranav Menon",
        "motherName": "Sunita Menon",
        "fatherName": "Rajesh Menon",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743813.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    },
    {
        "id": "STU-2024-030",
        "rollNo": "22287439",
        "dob": "01/01/2012",
        "name": "Nisha Yadav",
        "motherName": "Sunita Yadav",
        "fatherName": "Rajesh Yadav",
        "classLevel": "Class X",
        "schoolName": "Central Secondary School",
        "schoolCode": "84012",
        "centerCode": "4102",
        "session": "2023-2024",
        "issueDate": "20/05/2024",
        "pdfUrl": "https://raw.githubusercontent.com/nationalacademyonline/.in/main/CER/Result_PDFs/743912.pdf",
        "subjects": [
            {
                "code": "184",
                "name": "ENGLISH LANG & LIT",
                "theoryMarks": 72,
                "internalMarks": 19,
                "totalMarks": 91,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "002",
                "name": "HINDI COURSE-A",
                "theoryMarks": 68,
                "internalMarks": 18,
                "totalMarks": 86,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "041",
                "name": "MATHEMATICS STANDARD",
                "theoryMarks": 75,
                "internalMarks": 20,
                "totalMarks": 95,
                "maxMarks": 100,
                "grade": "A1",
                "gradePoint": 10
            },
            {
                "code": "086",
                "name": "SCIENCE",
                "theoryMarks": 70,
                "internalMarks": 19,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            },
            {
                "code": "087",
                "name": "SOCIAL SCIENCE",
                "theoryMarks": 71,
                "internalMarks": 18,
                "totalMarks": 89,
                "maxMarks": 100,
                "grade": "A2",
                "gradePoint": 9
            }
        ],
        "cgpa": 9.4,
        "totalMarksObtained": 450,
        "totalMaxMarks": 500,
        "percentage": 90.0,
        "resultStatus": "PASS",
        "division": "Pass with Distinction",
        "remarks": "Qualified"
    }
];
